# Generated by Django 4.2.1 on 2023-06-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='zone',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='zone_history',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.zone'),
        ),
    ]
