# Generated by Django 4.2.1 on 2023-06-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='level',
            field=models.PositiveIntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
